function [times, idx] = GenerateStartAndEndTimes(macTimes, durations, timezone)
        if (size(macTimes, 2) ~= 6) %throw error
            
        end
        import ovation.*
                       
        idx = find(macTimes(:,1) ~= -1);
        for n=1:length(idx)
                times{n}.endtime = datetime(macTimes(idx(n), 1),...
                                macTimes(idx(n), 2),...
                                macTimes(idx(n), 3),...
                                macTimes(idx(n), 4),...
                                macTimes(idx(n), 5),...
                                macTimes(idx(n), 6),...
                                0,...
                                timezone);
                times{n}.starttime = times{n}.endtime.minusMillis(durations(n)*1000);
        end
                 
end