function time = uniqueNumberToDateTime(uniqueNumber, timezoneName)
    
    if (size(uniqueNumber, 2) ~= 6) %throw error
        error('ovation:import:pds:date',...
            'Expected 6-element unique numbers for conversion to date/time');
    end
    
    import ovation.*
    
    time = datetime(uniqueNumber(1),...
            uniqueNumber(2),...
            uniqueNumber(3),...
            uniqueNumber(4),...
            uniqueNumber(5),...
            uniqueNumber(6),...
            0,...
            timezoneName);
        
    
end